### ISSUE TITLE
Create a New Solution does not copy/retain original `.cbuild-set.yml` from example

### ISSUE THREAD

**Issue by MiloradCvjetkovic** [ARM-software/vscode-cmsis-csolution#130]
Type: Bug Report

**Extension Version**: 1.44.0

**Description**

Using `Create a New Solution` button for copying example does not copy/retain original `.cbuild-set.yml` from example if such file already exists in the example, but the file gets created with only first context selected.

**Example**

`Fault.cbuild-set.yml` with the following content:
```
# Comment to see what happens with this file

cbuild-set:
  generated-by: vscode-cmsis-csolution version 1.44.0
  contexts:
    - context: Fault_S.Debug+B-U585I-IOT02A
    - context: Fault_NS.Debug+B-U585I-IOT02A
```

in the copied/created version looks like below:
```
cbuild-set:
  generated-by: vscode-cmsis-csolution version 1.44.0
  contexts:
    - context: Fault_S.Debug+STM32U585AIIx
```

**Expected behavior**

If the `.cbuild-set.yml` exists in the example it should be copied 1-to-1 to copy location and left untouched.
