### ISSUE TITLE
Add "Board: <name>" and "Device: <name>" to CMSIS view

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#134]
Add "Board: <name>" and "Device: <name>" at the beginning (before any projects are shown) of the CMSIS view.

![image](https://github.com/user-attachments/assets/ccd65049-a106-43cf-bf24-428c723ab583)

The information to show is in the `*.csolution.yml` file under `target-type:`.

On hover-over pack information from the `*.cbuild*.yml` files should be shown.
When expanded, the books should be shown.

CMSIS-Toolbox 2.7 adds the information about books as shown below. https://github.com/Open-CMSIS-Pack/csolution-examples -  CubeMX.csolution.yml is a good test project to get started.  Even when the information is part of the `cbuild.yml` I recommend to show it above the different projects.  In the IDE envionment all projects compile to the same target as `--context-set` is enforced. Only in a CI environment it is possible to compile for different targets.

```
build:
  generated-by: csolution version 2.7.0
  solution: CubeMX.csolution.yml
  project: CubeMX.cproject.yml
  context: CubeMX.Debug+MyBoard_ROM
  compiler: AC6
  board: B-U585I-IOT02A
  board-pack: Keil::B-U585I-IOT02A_BSP@2.0.0
  board-books:
    - name: https://www.st.com/en/evaluation-tools/B-U585I-IOT02A.html
      title: Discovery kit for IoT node with STM32U5 series
      category: overview
    - name: https://www.st.com/resource/en/schematic_pack/mb1551-u585i-c02_schematic.pdf
      title: Schematics revC-02
      category: schematic
    - name: https://www.st.com/resource/en/user_manual/um2839-discovery-kit-for-iot-node-with-stm32u5-series-stmicroelectronics.pdf
      title: User Manual
      category: manual
    - name: ${CMSIS_PACK_ROOT}/Keil/B-U585I-IOT02A_BSP/2.0.0/Documents/README.md
      title: Guide
      category: other
  device: STM32U585AIIx
  device-pack: Keil::STM32U5xx_DFP@3.0.0
  device-books:
    - name: https://www.st.com/resource/en/datasheet/stm32u585ai.pdf
      title: STM32U585xx Datasheet
    - name: https://developer.arm.com/documentation/100235/latest/
      title: Arm Cortex-M33 Devices
    - name: https://www.st.com/resource/en/reference_manual/rm0456-stm32u5-series-armbased-32bit-mcus-stmicroelectronics.pdf
      title: STM32U575/585 Arm-based 32-bit MCUs Reference Manual
  processor:
    dsp: on
    endian: little
    fpu: sp
    core: Cortex-M33
```
