### ISSUE TITLE
"Add Software Layer" does not consider fixed layers

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#137]
**Describe the bug**

1. When the `csolution.yml` file requires multiple layers, but defines already one layer, the VS Code layer detection overwrites it.
2. All targets are modified; only the current active target should be touched
3. Variables are entered multiple times

- Extension Version: 1.44 internal

**To Reproduce**

1. Use https://github.com/Arm-Examples/AWS_MQTT_Demo

2. Ensure that pack index is up-to-date with `cpackget update-index`

3. Set variables in `Demo.csolution.yml` to:
```yml
  target-types:
    - type: AVH
      board: ARM::V2M-MPS3-SSE-300-FVP
      variables:
        - Board-Layer: Board/AVH_MPS3_Corstone-300/Board.clayer.yml    # this variable gets overwritten
        - Shield-Layer: ""
    #       - Socket-Layer: ""
```

4. Open Folder in VS Code, this dialog should appear
![image](https://github.com/user-attachments/assets/5d471512-4523-4394-becc-5a15717fb369)

OK delivers this result:

```yml
      variables:
        - Board-Layer: Board/AVH_MPS3_Corstone-300/Board.clayer.yml
        - Shield-Layer: ""
        - Board-Layer: ""
        - Socket-Layer: $SolutionDir()$/Socket/VSocket/Socket.clayer.yml
    #       - Socket-Layer: ""
```

I would expect that the board layer is shown but in grey as it cannot be modified.  The result should not deliver two `Board-Layer` variables.

Another problem is that also the variables of the target-type MyBoard are modified, resulting in this:

```yml
    - type: MyBoard
      variables:
        - Board-Layer: ""
        - Socket-Layer: $SolutionDir()$/Socket/VSocket/Socket.clayer.yml
```

Expected is that only the current active target of the `context-set` is modified.

Using this process multiple times results in multiple settings of the same variable

```yml
    - type: MyBoard
      variables:
        - Board-Layer: ""
        - Socket-Layer: $SolutionDir()$/Socket/VSocket/Socket.clayer.yml
        - Board-Layer: ""
        - Socket-Layer: $SolutionDir()$/Socket/VSocket/Socket.clayer.yml
```

Expected:
  - The same variable should not be set twice.
  - Identical settings should not be written.
  - If the settings are different a good solution is to comment out the previous variable setting.
