### ISSUE TITLE
C/C++ language standard settings are not properly converted from Keil MDK project

### ISSUE THREAD

**Issue by Overlap0190** [ARM-software/vscode-cmsis-csolution#15]
Type: Bug Report

**Describe the bug**
- OS and Version: Windows 11 22H2 (Build 22621.963)
- VS Code Version: v1.74.2
- Extension Version: v0.9.0
- Target Device: Nuvoton M251
- Description: When using "Convert MDK project to csolution" the C/C++ language standard compiler flags are not set properly.

My settings in Keil MDK:
![grafik](https://user-images.githubusercontent.com/107535193/209140388-07073b1e-ba52-43cd-9a92-de789a434150.png)

After the conversion the *.csolution.yaml looks like this:
````
misc:
  - C*:
      - -fno-rtti
      - -funsigned-char
      - -fshort-enums
      - -fshort-wchar
      - -ffunction-sections
      - -std=c99
      ...
````
The C standard is applied to C/C++ files. The C++ standard is completely missing.

**To Reproduce**
1. Clone this repository https://github.com/RobertRostohar/Demo_EW/
2. Open the EdgeImpulse folder in VS Code
3. Convert the example.uvprojx to csolution
4. Open the generated example.csolution.yaml and the misc segment should look like mentioned above.

**Expected behavior**
I would expect something like this in the *.csolution.yaml:
````
misc:
  - C:
      - -std=c99
    CPP:
      - -std=c++14
    C*:
      - -fno-rtti
      - -funsigned-char
      - -fshort-enums
      - -fshort-wchar
      - -ffunction-sections
      ...
````
