### ISSUE TITLE
Device Vendor incorrectly mapped

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#152]
This problem happens only when the pack is not installed locally.

When using Create New with `board: Brainchip::ADK1000 miniPCIe:V1` the device vendor is incorrectly entered as 
`device: Brainchip::AKD1000`.

Correct is:
`device: BrainChip::AKD1000`.
[Blank_solution5.zip](https://github.com/user-attachments/files/18111955/Blank_solution5.zip)

**Comment by jkrech** [comment]
https://github.com/Arm-Debug/vscode-cmsis-csolution/pull/2022
`board:` and `device:` nodes are not specifying `Bvendor::` and `Dvendor::` respectively.

**Comment by jkrech** [comment]
Using internal CMSIS  Solution Extension build from main branch 2024-12-16 8:00 
a) Create new solution
b) Select BrainChip board ADK1000 miniPCIe
c) Select Project "Blank Solution"

```
  # List the packs that define the device and/or board.
  packs:
    - pack: Brainchip::AKD1000_DeviceFamilyPack
    - pack: ARM::CMSIS

  # List different hardware targets that are used to deploy the solution.
  target-types:
    - type: AKD1000
      board: ADK1000 miniPCIe:V1
      device: AKD1000
```

Board and Device are specified without vendor.
`cbuild setup` completes without error

Also checking that commands: `getDeviceName` and `getTargetPack` return correct information:
```
DEVICE: AKD1000 
PACK: Brainchip::AKD1000_DeviceFamilyPack@1.0.3
```
