### ISSUE TITLE
Arm® CMSIS Solution Can Not output xxx.hex and xxx.bin files!!!!! How should I set it?

### ISSUE THREAD

**Issue by vscodeenv** [ARM-software/vscode-cmsis-csolution#165]
![image](https://github.com/user-attachments/assets/9aad32ac-62bd-43d8-84d7-4436ee0fa2bb)

**Comment by ReinhardKeil** [comment]
Just add in `Project.cproject.yml` the `output:` node with:

```yml
   output:
     type:
       - elf
       - hex
       - bin
```

See: https://open-cmsis-pack.github.io/cmsis-toolbox/YML-Input-Format/#output
