### ISSUE TITLE
New solution workflow: Target type name ignored

### ISSUE THREAD

**Issue by KeilChris** [ARM-software/vscode-cmsis-csolution#171]
Type: Bug Report

**Description**

- OS and Version: MacOS 15.2.0
- VS Code Version: 1.96.3
- Extension Version: 1.46.0
- Target Device: B-U585-IOT02A

I have created a new CMSIS solution for the B-U585-IOT02A development board, based on the Blinky csolution example. I have entered a "Target Type" name for my target (MyHardware), but this name was ignored. In the generated csolution.yml file, I had this entry:
```yml
  # List different hardware targets that are used to deploy the solution.
  target-types:
    - type: B-U585I-IOT02A
      board: STMicroelectronics::B-U585I-IOT02A
      device: STMicroelectronics::STM32U585AIIx
```

**To Reproduce**
1. Go to 'Create new solution'.
2. 
3. Select B-U585-IOT02A.
4. Select "Blinky" Csolution example.
5. Enter "MyHardware" as **Target Type** (instead of STM32U585AIIx).
6. Click **Create**.

**Expected behavior**
The Blinky.csolution.yml file should show:
```yml
  # List different hardware targets that are used to deploy the solution.
  target-types:
    - type: MyHardware
      board: STMicroelectronics::B-U585I-IOT02A
      device: STMicroelectronics::STM32U585AIIx
```
