### ISSUE TITLE
Unable to change active context in multi-target and multi-project -solution

### ISSUE THREAD

**Issue by KimmoVaisanen-AlifSemi** [ARM-software/vscode-cmsis-csolution#176]
Type: Bug Report

**Describe the bug**
- OS and Version: Windows 11 or Ubuntu 22.04
- VS Code Version: 1.96.4
- Extension Version: 1.46.0
- Target Device: Alif Ensemble E7

We have a project (https://github.com/alifsemi/alif_mlek-cmsis-examples), which has two targets (HE and HP) and two projects (KWS and object detection), so that KWS is available only for HE core and object detection for HP core.

With CMSIS CSolution extension v1.46, user cannot change the active context (project selection does not work), but this works ok with extension version 1.44, so there is some kind of regression between these releases.

**To Reproduce**
1. Clone https://github.com/alifsemi/alif_mlek-cmsis-examples and open it with VSCode
2. Go to CMSIS extension
3. Click 'Manage Solution Settings'
4. Try to select 'Alif-E7-M55-HE' and 'kws'

**Expected behavior**
Active context is changed to Alif-E7-M55-HE and kws.

**Code sample and logs**

**Screenshots**
kws is not activated:

![Image](https://github.com/user-attachments/assets/a584bed1-ca9f-4356-85d7-b8f63d2be76d)

**Additional context**
This is a regression between v1.44 and v1.46.

**Comment by ReinhardKeil** [comment]
The `for-context:` in the *.csolution.yml file is causing the issue.  The extension has a problem with it and we will fix this in the release that is planned for end of Jan 2026.

As workaround comment the following lines. 

```yml
projects:
    - project: ./object-detection/object-detection.cproject.yml
#      for-context:
#       - +Alif-E7-M55-HP
    - project: ./kws/kws.cproject.yml
#     for-context:
#       - +Alif-E7-M55-H#175 
```
