### ISSUE TITLE
CMSIS View: Board and Device Vendor displayed inconsistently

### ISSUE THREAD

**Issue by RobertRostohar** [ARM-software/vscode-cmsis-csolution#191]
Type: Bug Report

**Describe the bug**
- OS and Version: Win11
- VS Code Version: 1.96.4
- Extension Version: 1.48
- Target Device: STMicroelectronics::STM32L4R9AIIx

CMSIS View displays the Board and Device Vendor inconsistently
- Board with vendor
- Device without Vendor

**To Reproduce**
Create a solution with a target which defines a board and device. For example:
```yml
  target-types:
    - type: STM32L4R9I-DISCO
      board: STMicroelectronics::STM32L4R9I-DISCO
      device: STMicroelectronics::STM32L4R9AIIx
```
Open the CMSIS View and check for Board and Device name

**Expected behavior**
Board and Device Vendor should be consistently shown or not show for both rather than a mixture.

**Screenshots**
![Image](https://github.com/user-attachments/assets/a6056bc7-afa0-485f-bc51-3c4373354745)
