### ISSUE TITLE
Using "Software Components" modifies or removes settings from different context

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#211]
**Problem**

A *.project.yml that has components with `for-context` attributes may loose settings.

**Duplicate**

1. Add to `*.cproject.yml` file for-context as shown below

```
  components:
    - component: CMSIS:CORE
    - component: CMSIS:RTOS2:Keil RTX5&Source
    - component: CMSIS:OS Tick:SysTick
      for-context: .Debug
    - component: CMSIS:OS Tick:SysTick
      for-context: .Release
```

2. Open "Manage Software Components" and add another component. This removes the component that is not in context.

**Environment**

arm.cmsis-csolution Version 1.50.0
