### ISSUE TITLE
Software Components change the compiler of .cbuild-run.yml and csolution.yml

### ISSUE THREAD

**Issue by sukiElaina** [ARM-software/vscode-cmsis-csolution#212]
I wan to use AC6@6.22.0，but when i changed the components, compiler settings of the config file  .cbuild-run.yml and csolution.yml changed into gcc

**Comment by jkrech** [comment]
Without looking at you CMSIS Solution project and having step by step instructions for reproducing your finding, it is hard to guess what has been going wrong for you.

a) Do you have the AC6 version 6.22.0 installed on  your host machine and the environment variable `AC6_TOOLCHAIN_6_22_0` pointing to the installation's bin folder? If you are using vcpkg in your shell or as part of the VS Code "Arm Tools Environment Manager" extension, you can control this via the `vcpkg-configuration.json` file.

b) In your CMSIS Solution project file `*.csolution.yml` the compiler is configured using the [`compiler:`](https://open-cmsis-pack.github.io/cmsis-toolbox/YML-Input-Format/#compiler) node.
What happens if you manually set `compiler: AC6@6.22.0` in your csolution.yml file? Do you see the correct compiler being used?

BTW: which versions of the CMSIS Solution extension and the CMSIS-Toolbox are you using?

**Comment by sukiElaina** [comment]
I use cubemx to generate my project.
this is my `vcpkg-configuration.json`:
```
{
 "registries": [
  {
   "name": "arm",
   "kind": "artifact",
   "location": "https://artifacts.tools.arm.com/vcpkg-registry"
  }
 ],
 "requires": {
  "arm:tools/kitware/cmake": "^3.28.4",
  "arm:tools/ninja-build/ninja": "^1.12.0",
  "arm:compilers/arm/armclang": "6.22.0",
  "arm:tools/open-cmsis-pack/cmsis-toolbox": "^2.7.0",
  "arm:debuggers/arm/armdbg": "6.2.1"
 }
}
```
this is my `csolution.yml` before i change my component:
```
solution:
  created-by: uv2csolution@1.6.0
  created-for: CMSIS-Toolbox@2.7.0
  compiler: AC6@6.22.0
  target-types:
    - type: H743v3
      device: STM32H743IITx
      optimize: debug
  projects:
    - project: H743v3.cproject.yml

```
when i use `Manage software components `,and add dsp library to my project:

![Image](https://github.com/user-attachments/assets/12c754a9-e8e1-42c9-a3a2-ab89579eb390)

then my `csolution.yml` file was automatically changed to:
```
solution:
  created-by: uv2csolution@1.6.0
  created-for: CMSIS-Toolbox@2.7.0
  compiler: GCC@6.22.0
  target-types:
    - type: H743v3
      device: STM32H743IITx
      optimize: debug
  projects:
    - project: H743v3.cproject.yml
```
this need to manually set `compiler: AC6@6.22.0` and then my project can work well.
