### ISSUE TITLE
"Select Compiler" configuration causes modification of defines in csolution.yml

### ISSUE THREAD

**Issue by VladimirUmek** [ARM-software/vscode-cmsis-csolution#217]
Type: Bug Report

**Describe the bug**
- OS and Version: Windows 11
- VS Code Version: 1.98.2
- Extension Version: Arm CMSIS Solution 1.50.0

I have a csolution.yml with select compiler options (and without compiler selected):
```yml
solution
  select-compiler:
    - compiler: AC6
    - compiler: GCC
    - compiler: CLANG
    - compiler: IAR
```
This same solution file has target types:
```yml
solution:
  target-types:
    - type: CM33
      device: ARMCM33
      define:
        - NS_APP_START_ADDRESS: 0x00200000
      variables:
        - Target-Layer: ../../../Target/CM33/Target.clayer.yml
```
When I open this solution with VS Code, CMSIS Solution extensions opens "Configure Solution" tab with "Select Compiler" options to select compiler. After I click "OK" my csolution.yml gets modified:
- compiler node is added
- all defines in target type get modified

The target type gets modified to:
```yml
    - type: CM33
      device: ARMCM33
      define:
        - NS_APP_START_ADDRESS: "2097152"
      variables:
        - Target-Layer: ../../../Target/CM33/Target.clayer.yml
```
**To Reproduce**
Use [CMSIS-FreeRTOS Examples](https://github.com/ARM-software/CMSIS-FreeRTOS/tree/bb1d1243182161ebad0ce0171c59c4351ec98fe9) to reproduce the behavior. Open "Examples" directory with VS Code.

**Expected behavior**
Only compiler node shall be added, the rest of the solution file shall be unmodified.
