### ISSUE TITLE
Clangd does not recognize Armclang-specific flags like `-ffp-mode=full`

### ISSUE THREAD

**Issue by jthuangarm** [ARM-software/vscode-cmsis-csolution#237]
Type: Bug Report

**Describe the bug**
I would like to use some compiler options specific to **Armclang** in the `*.cproject.yml` file. For example:

```
  setups:
    - setup: Options
      misc:
        - C-CPP:
            - -ffp-mode=full
      ...
```

However, these options for FPU are not recognized by **Clangd**. As a result, when opening arbitrary source files, the following error message is always displayed:

![Image](https://github.com/user-attachments/assets/11683724-22fb-4bc8-b223-833e9b2447dd)

**Temporary Workaround**
A practical workaround is to manually add the `Remove:` node directly in the `.clangd` file. This tells Clangd to ignore unsupported flags during the analysis process, while keeping them intact for the Arm compilation process. Most importantly, this manual change will not be overwritten afterwards. For reference,

```
CompileFlags:
  CompilationDatabase: ...\Blinky\out\Blinky\CM0p
  Remove: 
    - '-ffp-mode=*'
  Add:
    - '-D_ILP32=1'
    - '-D_USE_STATIC_INLINE=1'
  ...
```
Further details about supported Clangd options can be found in:
https://clangd.llvm.org/config.html
