### ISSUE TITLE
Multiproject - Manage Solution - Active Projects

### ISSUE THREAD

**Issue by FerdinandEn** [ARM-software/vscode-cmsis-csolution#62]
Type: Bug Report

**Describe the bug**
OS and Version: Windows 11
VS Code Version: 1.88
CMSIS Solution 1.34.3

I have a multiproject for my student teaching placement. I was able to open and convert the entire project.

Within the project it was not possible to change the active project under Manage Solution. By adjusting the entry in Praktikum.cbuild-set.yml, it was possible to switch. It was then also possible to adjust the targets in Manage Solution.

**Comment by jkrech** [comment]
Could you please provide a reproducer. 
If I understand you correctly the initial configuration via the Manage Solution editor was impossible. What was displayed?
After you had edited the file manually you were able to configure the contexts via Manage Solutions.

Note: you can also update the cbuild-set.yml file via the commandline using e.g. `csolution convert Praktikum.csolution.yml -S -c <context1> -c <context2>`

**Comment by FerdinandEn** [comment]
I have created and uploaded an example. The project was first created with uVision and then the multi-project was converted to VSC (The screenshot was created after generating).

[Multitest.zip](https://github.com/ARM-software/vscode-cmsis-csolution/files/15058685/Multitest.zip)

![image](https://github.com/ARM-software/vscode-cmsis-csolution/assets/21216218/8f12500f-429f-4837-b6f9-40c7e20b4cae)

![image](https://github.com/ARM-software/vscode-cmsis-csolution/assets/21216218/33c20cdb-d5d6-4bca-8040-0b95862e9180)

**Comment by jkrech** [comment]
The reason why the project2 is not selectable is because the uv2csolution converter has created two different `target-type` entries for project1 ("Proj1_Target1") and for project2 ("Proj2_Target1") . The Manage Solution is designed to only allow to build a single `target-type` at a time.

At this point you will need to manually edit the csolution.yml file using the same target-type name for both project1 and project2.

generated:
```
    - project: Project1/project1.cproject.yml
      for-context:
        - +Proj1_Target_1
        - +Proj1_Target_2
        - +Proj1_Target_3
    - project: Project2/project2.cproject.yml
      for-context:
        - +Proj2_Target_1
        - +Proj2_Target_2
        - +Proj2_Target_3
```

If you know that both uvprojx files for project1.uvprojx and project2.uvprojx are configured identical you can remove the Prj2_Target_n target-types and share the target-type.
```
    - project: Project1/project1.cproject.yml
    - project: Project2/project2.cproject.yml
```
