### ISSUE TITLE
Software Components from Layers not shown when variables are used to define the layer.

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#83]
- Extension Version: CMSIS-Solution 1.40

**To Reproduce**

Use an solution that defines layers via variables.  The components that are defined in the layer are not shown in the Software Components view.

![image](https://github.com/user-attachments/assets/a3012888-f395-4597-aa9f-84eeeac13d85)

**Workaround**

Replace the variable in the `cproject.yml` file with the actual path to the `clayer.yml` file, for example:

```yml
  layers:
    - layer: ../Board/B-U585I-IOT02A/Board.clayer.yml
      type: Board
```

Software components that are defined in the `clayer.yml` file are then shown, but cannot be modified.

![image](https://github.com/user-attachments/assets/fce83030-6365-47bd-a580-3bcafc7f9b70)
