### ISSUE TITLE
Templates with multiple targets

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/vscode-cmsis-csolution#96]
The pack https://github.com/VladimirUmek/NXP_FRDM-MCXN947_BSP/releases contains a template with two targets: "Device with RAM/ROM".  This enables configurations with a Flash (ROM) and RAM target that can be easily selected by using the Manage Solution / Context Set dialog.

The template is registered here: 
https://github.com/VladimirUmek/NXP_FRDM-MCXN947_BSP/blob/main/NXP.FRDM-MCXN947_BSP.pdsc#L1750

It effectively defines targets with:

```yml
  # List different hardware targets that are used to deploy the solution.
  target-types:
    - type: %Name%_ROM
      variables:
        - LinkerScript: <script_for_ROM>

    - type: %Name%_RAM
      variables:
        - LinkerScript:: <script_for_RAM>
```

In the moment, the VSCode extension cannot handle this type of templates.  We should define how we extend it.
